version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Imagen base con Docker instalado
    steps:
      - checkout  # Descargar el código del repositorio

      - setup_remote_docker:  # Configurar Docker en el entorno de CircleCI
          docker_layer_caching: true

      - run:
          name: Construir la imagen de Docker
          command: |
            docker build -t automation-opencart .

      - run:
          name: Ejecutar pruebas
          command: |
            docker run --rm automation-opencart

      - store_artifacts:
          path: /home/seluser/reports/report.html  # Guardar el reporte de pruebas como artefacto

      - store_artifacts:
          path: /home/seluser/reports/screenshots  # Guardar las capturas de pantalla como artefacto