version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout  # Descargar el código del repositorio

      - run:
          name: Instalar dependencias de Python
          command: |
            pip install --no-cache-dir -r requirements.txt

      - run:
          name: Ejecutar pruebas
          command: |
            pytest tests/ --html=reports/report.html --self-contained-html

      - store_artifacts:
          path: reports/report.html  # Guardar el reporte de pruebas como artefacto

      - store_artifacts:
          path: screenshots/  # Guardar las capturas de pantalla como artefacto