version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.4-browsers  # Imagen con Chrome preinstalado
    environment:
      CIRCLECI: "true"  # Activamos la detección de CI
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install webdriver-manager==3.8.6  # Versión compatible
      - run:
          name: Ejecutar pruebas
          command: |
            mkdir -p reports screenshots
            pytest tests/ --html=reports/report.html --self-contained-html
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: screenshots